# Generated by Django 4.2.16 on 2024-10-11 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0002_alter_users_average_time_alter_users_prev_10_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='puzzle',
            old_name='current_time',
            new_name='puzzle_time',
        ),
    ]
