# Generated by Django 4.2.16 on 2024-10-11 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0003_rename_current_time_puzzle_puzzle_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='name',
            field=models.CharField(default=2, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
