# Generated by Django 4.2.16 on 2024-10-11 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0006_alter_puzzle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='puzzle_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='users',
            name='total_time',
            field=models.FloatField(default=0),
        ),
    ]
